name: unittests
on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        mpi_install: [system, conda]
        python: [3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python }}
          channels: conda-forge
      - run: conda --version
      - run: which python
      - run: ./ci/install_mpi.sh
        env:
          MPI_INSTALL: ${{ matrix.mpi_install }}
      - run: pip install pytest pytest-env
      - run: pip install -e .
      - run: echo "localhost slots=16">hostfile
      - run: pytest