name: unittests
on:
  pull_request:
  push:
    branches: main

jobs:
  test:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        mpi_install: [system, conda]
        python: [3.8]
    env:
      DICODILE_DATA_HOME: ${{ env.HOME }}/data
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python }}
          channels: conda-forge
      - name: Cache test data
        uses: actions/cache@v2
        env:
          cache-name: cache-test-data
        with:
          path: ${{ env.DICODILE_DATA_HOME }}
          key: ${{ env.cache-name }}
      - name: Install MPI
        run: |
          conda --version
          which python
          ./ci/install_mpi.sh
        env:
          MPI_INSTALL: ${{ matrix.mpi_install }}
      - name: Run unit tests
        run: |
          pip install -e .[test]
          echo "localhost slots=16">hostfile
          pytest --cov-report=xml --cov=dicodile
      - name: Upload coverage
        uses: codecov/codecov-action@v1
        with:
          flags: unittests 
          fail_ci_if_error: true 
          verbose: true
